# Generated by Django 4.2.3 on 2023-07-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_image', models.ImageField(default='assets/zebby.jpg', upload_to='brand-logo/')),
                ('brand_name', models.CharField(max_length=256)),
                ('brand_description', models.TextField()),
                ('no_of_shoes_available', models.PositiveIntegerField()),
                ('brand_in_stock', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.TextField(max_length=50)),
                ('time_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_number', models.CharField(max_length=50)),
                ('time_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_image', models.ImageField(height_field='image_height', upload_to='shoes/', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('shoe_name', models.CharField(max_length=256)),
                ('shoe_gender', models.TextField()),
                ('shoe_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shoe_in_stock', models.BooleanField(default=False)),
                ('shoe_price_was', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('shoe_time_added', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.brand')),
                ('shoe_color_available', models.ManyToManyField(to='brands.color')),
                ('shoe_size', models.ManyToManyField(blank=True, to='brands.size')),
            ],
        ),
    ]
