# Generated by Django 4.2 on 2023-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=256)),
                ('brand_description', models.TextField()),
                ('no_of_shoes_available', models.PositiveIntegerField()),
                ('brand_in_stock', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
