# Generated by Django 4.2 on 2023-05-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jordan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_image', models.ImageField(height_field='image_height', upload_to='product-images/', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('shoe_name', models.CharField(max_length=256)),
                ('shoe_gender', models.TextField()),
                ('shoe_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shoe_in_stock', models.BooleanField(default=False)),
                ('shoe_color_available', models.ManyToManyField(to='brands.color')),
            ],
        ),
    ]
