# Generated by Django 4.2 on 2023-05-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_color_jordan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jordan',
            name='shoe_time_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
