# Generated by Django 4.2 on 2023-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_jordan_shoe_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='jordan',
            name='shoe_price_was',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
