# Generated by Django 4.2 on 2023-05-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_jordan_shoe_price_was'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_image', models.ImageField(height_field='image_height', upload_to='jordans/', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('shoe_name', models.CharField(max_length=256)),
                ('shoe_gender', models.TextField()),
                ('shoe_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('shoe_in_stock', models.BooleanField(default=False)),
                ('shoe_price_was', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('shoe_time_added', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brands')),
                ('shoe_color_available', models.ManyToManyField(to='brands.color')),
            ],
        ),
        migrations.DeleteModel(
            name='Jordan',
        ),
    ]
