# Generated by Django 4.2 on 2023-05-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_shoes_delete_jordan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoes',
            new_name='Shoe',
        ),
    ]
