# Generated by Django 4.2 on 2023-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_rename_shoes_shoe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_image',
            field=models.ImageField(height_field='image_height', upload_to='shoes/', width_field='image_width'),
        ),
    ]
