# Generated by Django 4.2 on 2023-06-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0012_alter_shoe_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shoe',
            new_name='Product',
        ),
    ]
