# Generated by Django 4.2.3 on 2023-07-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0013_rename_shoe_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_time_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
