# Generated by Django 4.2.3 on 2023-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0015_rename_color_time_added_color_time_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_number', models.CharField(max_length=50)),
                ('time_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.ManyToManyField(to='brands.size'),
        ),
    ]
