# Generated by Django 4.2 on 2023-06-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='assets/default-profile-pic.png', height_field='image_height', upload_to='user_profiles/', width_field='image_width'),
        ),
    ]
