# Generated by Django 4.2.3 on 2023-08-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0006_testing_rename_comments_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
