# Generated by Django 4.2.3 on 2023-08-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0007_delete_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(default='Top Gz customer', max_length=25),
        ),
    ]
