# Generated by Django 4.2.3 on 2023-08-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0008_comment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
