# Generated by Django 4.2.3 on 2023-08-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0009_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(blank=True, default='Top Gz customer', max_length=25, null=True),
        ),
    ]
