# Generated by Django 4.2.3 on 2023-07-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0009_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
