# Generated by Django 4.2.3 on 2023-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0010_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
