# Generated by Django 4.2.3 on 2023-08-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0010_alter_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
