# Generated by Django 4.2.3 on 2023-07-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0013_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
