# Generated by Django 4.2.3 on 2023-07-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0018_alter_product_shoe_size'),
        ('theorders', '0014_remove_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.product'),
        ),
    ]
