# Generated by Django 4.2 on 2023-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0007_rename_brands_brand_alter_shoe_shoe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(default='assets/topg-logo.gif', height_field='image_height', upload_to='brand-logos/', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
