# Generated by Django 4.2 on 2023-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0010_remove_brand_brand_image_remove_brand_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(default='assets/zebby.jpg', upload_to='brand-logo/'),
        ),
    ]
