# Generated by Django 4.2 on 2023-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0002_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(default='Kenya', max_length=250, null=True),
        ),
    ]
