# Generated by Django 4.2 on 2023-07-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theorders', '0006_order_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
