# Generated by Django 4.2.3 on 2023-07-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0016_size_product_shoe_size'),
        ('theorders', '0012_remove_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.size'),
        ),
    ]
